### ISSUE TITLE
License Query

### ISSUE THREAD

**Issue by darigovresearch** [londonhackspace/acnode-dashboard#7]
Many people have inquired on the mailing list and in person (when that was possible) to be able to use the ac node/doorbot system for their own hackspace or other office. Would be helpful to have a license so it's clear what reuse is allowed for the code and hardware associated to the project.

May also encourage people to make fixes, new feature improvements and contribute back with pull requests.

Can anyone advise on what the license of this repository and the associated repositories?

**Comment by mich181189** [comment]
This one is an easy one since it's all my work. The others are more of a mix of different contributions so might be harder to pin down. 

This repo is also the least likely to be needed on most systems - it's purely a monitoring system to keep track of the health of a large number of nodes in one place. It's also under very heavy development, and while it isn't super hard to deploy, there are a lot of moving parts since it takes inputs from so many places (and that's only going to increase!)

I'll stick a license note in this one on my next round of changes.

**Comment by darigovresearch** [comment]
@mich181189 thanks for the clarification and for considering putting a license on this repo 

It may make sense to have a consistent compatible license across the three repositories from an integration point of view
